name: CMake

on:
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ env.BUILD_TYPE }}
        max-size: 1000M
    
    - name: Add OpenMW PPA Dependancies
      run: sudo add-apt-repository ppa:openmw/openmw; sudo apt-get update
    
    - name: Install Building Dependancies
      run: sudo CI/install_debian_deps.sh gcc openmw-deps openmw-deps-dynamic

    - name: Configure CMake
      run: cmake -S . -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=./install

    - name: Build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --build . --config ${{env.BUILD_TYPE}} --parallel 3
 
    - name: Install OpenMW
      shell: bash
      run: cmake --install .
      
    - name: Create OpenMW Artifact Zip
      shell: bash
      working-directory: install
      run: |
        ls -laR
        7z a ../build_artifact.7z .
        
    - name: Upload Zip
      uses: actions/upload-artifact@v1
      with:
        path: ./build_artifact.7z
        name: build_artifact.7z
