name: CMake

on:
  pull_request:
    branches: [ master ]

env:
  CONFIGURATION: RelWithDebInfo
  GOOGLETEST_DIR: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Add OpenMW PPA Dependancies
      run: sudo add-apt-repository ppa:openmw/openmw; sudo apt-get update
    
    - name: Install Building Dependancies
      run: sudo CI/install_debian_deps.sh gcc openmw-deps openmw-deps-dynamic

    - name: Prime ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ env.CONFIGURATION }}
        max-size: 1000M

    - name: Install gtest
      run: sudo CI/build_googletest.sh

    - name: Configure
      run: cmake -S . -B . -DGTEST_ROOT="$(pwd)/googletest/build/install" -DGMOCK_ROOT="$(pwd)/googletest/build/install" -DBUILD_UNITTESTS=ON -DCMAKE_BUILD_TYPE=${{env.CONFIGURATION}} -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_FLAGS='-Werror' -DCMAKE_CXX_FLAGS="-Werror -Wno-error=deprecated-declarations -Wno-error=nonnull -Wno-error=deprecated-copy"

    - name: Build
      run: cmake --build . --config ${{env.CONFIGURATION}} --parallel 3
 
    - name: Test
      run: ./openmw_test_suite

#    - name: Install
#      shell: bash
#      run: cmake --install .
      
#    - name: Create Artifact
#      shell: bash
#      working-directory: install
#      run: |
#        ls -laR
#        7z a ../build_artifact.7z .
        
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v1
#      with:
#        path: ./build_artifact.7z
#        name: build_artifact.7z
